<?
    // Set up page title:
    $this->headTitle($this->translate('User Account'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('Account') . '</em>';
?>
<h2><?=$this->transEsc('User Account')?></h2>
<?=$this->flashmessages()?>

<form method="post" action="" name="accountForm" id="accountForm">
  <?=$this->auth()->getCreateFields()?>
  <button class="button" type="submit" name="submit" value="<?=$this->transEsc('Submit')?>"><?=$this->transEsc('Submit')?></button>
  
</form>
<?
  // Set up form validation:
  $initJs = '$(document).ready(function() { $(\'#accountForm\').validate(); });';
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $initJs);
?>