<? $user = $this->auth()->isLoggedIn(); ?>
<div class="bulkActionButtons panel clearfix">
  <label class="left" for="addFormCheckboxSelectAll"><input type="checkbox" class="selectAllCheckboxes left" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/> <?=$this->transEsc('select_page')?></label>
  <span class="left">|</span>
  <span class="left"><strong><?=$this->transEsc('with_selected')?>: </strong></span>
  <ul class="button-group">
    <li><button type="submit" class="mail tiny" name="email" value="<?=$this->transEsc('Email')?>" title="<?=$this->transEsc('email_selected')?>"><i class="fa-envelope"></i><?=$this->transEsc('Email')?></button></li>
    <? if ((!is_null($this->list) && $this->list->editAllowed($user)) || is_null($this->list) && $user): ?>
      <li><button id="<?=$this->idPrefix?>delete_list_items_<?=!is_null($this->list) ? $this->escapeHtml($this->list->id) : ''?>" type="submit" class="delete tiny" name="delete" value="<?=$this->transEsc('Delete')?>" title="<?=$this->transEsc('delete_selected')?>"><i class="fa-minus-circle"></i><?=$this->transEsc('Delete')?></button></li>
    <? endif; ?>
    <? $exportOptions = $this->export()->getBulkOptions(); if (count($exportOptions) > 0): ?>
      <li><button type="submit" class="export tiny" name="export" value="<?=$this->transEsc('Export')?>" title="<?=$this->transEsc('export_selected')?>"><i class="fa-external-link"></i><?=$this->transEsc('Export')?></button></li>
    <? endif; ?>
    <li><button type="submit" class="print tiny" name="print" value="<?=$this->transEsc('Print')?>" title="<?=$this->transEsc('print_selected')?>"><i class="fa-print"></i><?=$this->transEsc('Print')?></button></li>
    <? if ($this->cart()->isActive()): ?>
      <li><button id="<?=$this->idPrefix?>updateCart" type="submit" class="button bookbagAdd" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"><i class="fa-plus-square-o"></i><?=$this->transEsc('Add to Book Bag')?></button></li>
    <? endif; ?>
  </ul>
</div>
