<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Configuration'));
?>
<div class="sidebar large-3 columns">
  <?=$this->render("admin/menu.phtml")?>
</div>

<div class="main large-9 columns">
  <h1><?=$this->transEsc('Configuration')?></h1>
  <?=$this->flashmessages()?>
  <p>Most VuFind configuration is handled by editing the configuration files in <strong><?=$this->escapeHtml($this->baseConfigPath)?></strong>.</p>
  <p>Some basic settings can also be adjusted through the auto-configuration tool.</p>
  <? if (!$this->showInstallLink): ?>
    <p><?=$this->transEsc('Auto configuration is currently disabled') ?>.</p>
    <p><a href="<?=$this->url('admin-enableautoconfig')?>"><?=$this->transEsc('Enable Auto Config')?></a></p>
  <? else: ?>
    <p><a href="<?=$this->url('install-home')?>"><?=$this->transEsc('auto_configure_title')?></a></p>
  <? endif; ?>
</div>

