<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - System Maintenance'));
?>
<div class="sidebar large-3 columns">
  <?=$this->render("admin/menu.phtml")?>
</div>

<div class="main large-9 columns">
  <h1><?=$this->transEsc('System Maintenance')?></h1>

  <h2>Utilities</h2>
  <?=$this->flashmessages()?>
  <form method="get" action="<?=$this->url('admin-deleteexpiredsearches')?>">
    <label for="del_daysOld" style="font-weight: normal;">Delete unsaved user search histories older than</label>
    <input id="del_daysOld" type="text" name="daysOld" size="5" value="2"/> days.
    <button type="submit" name="submit" value="<?=$this->transEsc('Submit')?>"><?=$this->transEsc('Submit')?></button>
  </form>
</div>


