<?
    $addThis = $this->addThis();
    if (!empty($addThis)) {
        $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
    }

    // Set up some variables for convenience:
    $id = $this->driver->getUniqueId();
    $controllerClass = 'controller' . $this->record($this->driver)->getController();
    $cart = $this->cart();
    $cartId = $this->driver->getResourceSource() . '|' . $id;
?>
<div class="toolbar">
  <ul class="button-group">
    <? if (count($this->driver->getCitationFormats()) > 0): ?>
      <li><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" class="button tiny citeRecord cite <?=$controllerClass?>" id="citeRecord" title="<?=$this->transEsc('Cite this')?>"><i class="fa-book"></i><?=$this->transEsc('Cite this')?></a></li>
    <? endif; ?>
    <li><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'SMS')?>" class="button tiny smsRecord sms <?=$controllerClass?>" id="smsRecord" title="<?=$this->transEsc('Text this')?>"><i class="fa-mobile"></i><?=$this->transEsc('Text this')?></a></li>
    <li><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" class="button tiny mailRecord mail <?=$controllerClass?>" id="mailRecord" title="<?=$this->transEsc('Email this')?>"><i class="fa-envelope"></i><?=$this->transEsc('Email this')?></a></li>
    <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); if (count($exportFormats) > 0): ?>
    <li>
      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" class="button tiny export exportMenu"><i class="fa-external-link"></i><?=$this->transEsc('Export Record')?></a>
      <ul class="menu offscreen" id="exportMenu">
      <? foreach ($exportFormats as $exportFormat): ?>
        <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtml($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtml($exportFormat)?>"><?=$this->transEsc('Export to')?> <?=$this->escapeHtml($exportFormat)?></a></li>
      <? endforeach; ?>
      </ul>
    </li>
    <? endif; ?>
    <li id="saveLink"><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" class="button tiny saveRecord fav <?=$controllerClass?>" id="saveRecord" title="<?=$this->transEsc('Add to favorites')?>"><i class="fa-heart"></i><?=$this->transEsc('Add to favorites')?></a></li>
    <? if (!empty($addThis)): ?>
    <li id="addThis"><a class="button tiny addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa-bookmark"></i><?=$this->transEsc('Bookmark')?></a></li>
    <? endif; ?>
    <? if ($cart->isActive()): ?>
      <li><a id="recordCart" class="button tiny <?=$cart->contains($cartId) ? 'bookbagDelete' : 'bookbagAdd'?> offscreen" href="#"><i class="fa-plus-square-o"></i><?=$this->transEsc('Add to Book Bag')?></a></li>
    <? endif; ?>
  </ul>
  <? if ($cart->isActive()): ?>
    <div class="cartSummary">
      <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
        <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtml($cartId)?>" />
        <noscript>
          <? if ($cart->contains($cartId)): ?>
            <button type="submit" class="tiny cart bookbagDelete" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"><i class="fa-minus-circle"></i><?=$this->transEsc('Remove from Book Bag')?></button>
          <? else: ?>
            <button type="submit" class="tiny bookbagAdd" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"><i class="fa-plus-square-o"></i><?=$this->transEsc('Add to Book Bag')?></button>
          <? endif; ?>
        </noscript>
      </form>
    </div>
  <? endif; ?>
</div>
