<? if (!isset($this->hideCartControls) && $this->cart()->isActive()): ?>
  <div class="bulkActionButtons">
    <input type="checkbox" class="selectAllCheckboxes left" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/> <label class="left" for="<?=$this->idPrefix?>addFormCheckboxSelectAll"><?=$this->transEsc('select_page')?></label>
    <span class="left">|</span>
    <span class="left"><strong><?=$this->transEsc('with_selected')?>: </strong></span>
    <button id="<?=$this->idPrefix?>updateCart" type="submit" class="tiny left bookbagAdd" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"><i class="fa-plus-square-o"></i><?=$this->transEsc('Add to Book Bag')?></button>
  </div>
<? endif; ?>
