<? if ($this->pageCount): ?>
  <ul class="pagination">
  <? if (isset($this->previous)): ?>
    <li>
    <a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>">[1]</a></li>
    <li class="arrow"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>">&laquo; <?=$this->transEsc('Prev')?></a></li>
  <? endif; ?>

  <? if (count($this->pagesInRange) > 1): ?>
    <? foreach ($this->pagesInRange as $page): ?>
      <li<?=($page == $this->current)? ' class="current"' : '' ?>><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
    <? endforeach; ?>
  <? endif; ?>

  <? if (isset($this->next)): ?>
    <li class="arrow"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><?=$this->transEsc('Next');?> &raquo;</a></li>
    <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>">[<?=$this->pageCount?>]</a></li>
  <? endif; ?>
  </ul>
<? endif; ?>