<? $results = $this->recommend->getResults(); ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); ?>

<? if (isset($sideFacetSet['lists']) && !empty($sideFacetSet['lists']['list'])): ?>
  <div class="sidegroup">
    <h4 class="list"><?=$this->transEsc($sideFacetSet['lists']['label'])?></h4>
    <ul class="side-nav favorites">
      <? foreach ($sideFacetSet['lists']['list'] as $current): ?>
        
        <? if ($current['isApplied']): ?>
          <li class="active"><a href="#"><?=$this->escapeHtml($current['displayText'])?></a>
        <? else: ?>
          <li><a href="<?=$this->url('userList', array('id' => $current['value']))?>"><?=$this->escapeHtml($current['displayText'])?></a>
        <? endif; ?>
        (<?=$this->escapeHtml($current['count'])?>)
        </li>
      <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>

<? if (isset($sideFacetSet['tags']) && !empty($sideFacetSet['tags']['list'])): ?>
  <div class="sidegroup">
    <h4 class="tag"><?=$this->transEsc($sideFacetSet['tags']['label'])?></h4>
    <? $filterList = $results->getParams()->getFilterList(true);
       $tagFilterList = isset($filterList[$sideFacetSet['tags']['label']]) ? $filterList[$sideFacetSet['tags']['label']] : null;
       if (!empty($tagFilterList)): ?>
      <strong><?=$this->transEsc('Remove Filters')?></strong>
      <ul class="filters side-nav">
      <? $field = $sideFacetSet['tags']['label'];
         foreach ($tagFilterList as $filter): ?>
        <? $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value']); ?>
        <li>
          <a href="<?=$removeLink?>"><img src="<?=$this->imageLink('silk/delete.png')?>" alt="<?=$this->transEsc('Delete') ?>"/></a>
          <a href="<?=$removeLink?>"><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?></a>
        </li>
      <? endforeach; ?>
      </ul>
    <? endif; ?>
    <ul>
      <? foreach ($sideFacetSet['tags']['list'] as $thisFacet): ?>
        <li>
        <? if ($thisFacet['isApplied']): ?>
          <?=$this->escapeHtml($thisFacet['displayText'])?> <img src="<?=$this->imageLink('silk/tick.png')?>" alt="<?=$this->transEsc('Selected') ?>"/>
        <? else: ?>
          <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet('tags', $thisFacet['value'])?>"><?=$this->escapeHtml($thisFacet['displayText'])?></a> (<?=$this->escapeHtml($thisFacet['count'])?>)
        <? endif; ?>
        </li>
      <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>

